version: "3.9"
services:
  arcgis-exb:
    image: dspriggs/arcgis-exb:1.13
    container_name: arcgis-exb
    ports:
      - "80:3000"
      - "443:3001"
    volumes:
      - ./server/public:/home/node/ArcGISExperienceBuilder/server/public
      - ./client:/home/node/ArcGISExperienceBuilder/client
  portainer:
    image: portainer/portainer-ce:latest
    container_name: portainer
    restart: "no"
    command: -H unix:///var/run/docker.sock
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer-storage:/data
    ports:
      - "9443:9443"
volumes:
  portainer-storage:
